version = "15.0.*"
# This is the official web portal for GDB,
# see https://sourceware.org/gdb/current/ for other ways of obtaining the source code.
upstream_repository = "https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=tree"
extra_description = """\
  Type hints for GDB's \
  [Python API](https://sourceware.org/gdb/onlinedocs/gdb/Python-API.html). \
  Note that this API is available only when running Python scripts under GDB: \
  it is not possible to install the `gdb` package separately, for instance \
  using `pip`.\
"""

[tool.stubtest]
platforms = ["linux"]
apt_dependencies = ["gdb"]
# stubtest fails for unknown reasons after upgrading to use Python 3.12:
#
# Traceback (most recent call last):
#   File "/tmp/stubtest-4m851njl/gdb_stubtest.py", line 22, in <module>
#     from mypy.stubtest import main
#   File "/tmp/stubtest-4m851njl/lib/python3.12/site-packages/mypy/stubtest.py", line 30, in <module>
#     from pathlib import Path
#   File "/usr/lib/python3.12/pathlib.py", line 19, in <module>
#     from urllib.parse import quote_from_bytes as urlquote_from_bytes
#   File "/usr/lib/python3.12/urllib/parse.py", line 36, in <module>
#     import math
# ModuleNotFoundError: No module named 'math'
skip = true
